version: '3'
services:
  web:
    build: ./src
    ports:
      - 80:80
    expose:
      - 80/tcp
    restart: always
  db:
    build: ./database
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foro
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_DATABASE: foro
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data: